// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.24.0
// source: protos/recommend_service.proto

package RecommendationService

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// input item representing the id of an anime that the user watched in the past
type Item struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *Item) Reset() {
	*x = Item{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_recommend_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Item) ProtoMessage() {}

func (x *Item) ProtoReflect() protoreflect.Message {
	mi := &file_protos_recommend_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Item.ProtoReflect.Descriptor instead.
func (*Item) Descriptor() ([]byte, []int) {
	return file_protos_recommend_service_proto_rawDescGZIP(), []int{0}
}

func (x *Item) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

// Recommended item
type RecommendedItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// item id
	Id uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// computed score of this item
	Score float32 `protobuf:"fixed32,2,opt,name=score,proto3" json:"score,omitempty"`
}

func (x *RecommendedItem) Reset() {
	*x = RecommendedItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_recommend_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RecommendedItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecommendedItem) ProtoMessage() {}

func (x *RecommendedItem) ProtoReflect() protoreflect.Message {
	mi := &file_protos_recommend_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecommendedItem.ProtoReflect.Descriptor instead.
func (*RecommendedItem) Descriptor() ([]byte, []int) {
	return file_protos_recommend_service_proto_rawDescGZIP(), []int{1}
}

func (x *RecommendedItem) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *RecommendedItem) GetScore() float32 {
	if x != nil {
		return x.Score
	}
	return 0
}

// anime recommendation request body
type WatchedAnime struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// list of ids of watched animes
	Items []*Item `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	// desired number of recommendations
	K *int32 `protobuf:"varint,2,opt,name=k,proto3,oneof" json:"k,omitempty"`
}

func (x *WatchedAnime) Reset() {
	*x = WatchedAnime{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_recommend_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WatchedAnime) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchedAnime) ProtoMessage() {}

func (x *WatchedAnime) ProtoReflect() protoreflect.Message {
	mi := &file_protos_recommend_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchedAnime.ProtoReflect.Descriptor instead.
func (*WatchedAnime) Descriptor() ([]byte, []int) {
	return file_protos_recommend_service_proto_rawDescGZIP(), []int{2}
}

func (x *WatchedAnime) GetItems() []*Item {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *WatchedAnime) GetK() int32 {
	if x != nil && x.K != nil {
		return *x.K
	}
	return 0
}

// Response to an anime recommendation request
type RecommendedAnime struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	//list of recommended items
	Items []*RecommendedItem `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
}

func (x *RecommendedAnime) Reset() {
	*x = RecommendedAnime{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protos_recommend_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RecommendedAnime) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecommendedAnime) ProtoMessage() {}

func (x *RecommendedAnime) ProtoReflect() protoreflect.Message {
	mi := &file_protos_recommend_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecommendedAnime.ProtoReflect.Descriptor instead.
func (*RecommendedAnime) Descriptor() ([]byte, []int) {
	return file_protos_recommend_service_proto_rawDescGZIP(), []int{3}
}

func (x *RecommendedAnime) GetItems() []*RecommendedItem {
	if x != nil {
		return x.Items
	}
	return nil
}

var File_protos_recommend_service_proto protoreflect.FileDescriptor

var file_protos_recommend_service_proto_rawDesc = []byte{
	0x0a, 0x1e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x72, 0x65, 0x63, 0x6f, 0x6d, 0x6d, 0x65,
	0x6e, 0x64, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x04, 0x6d, 0x61, 0x6b, 0x69, 0x22, 0x16, 0x0a, 0x04, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x69, 0x64, 0x22, 0x37,
	0x0a, 0x0f, 0x52, 0x65, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x64, 0x65, 0x64, 0x49, 0x74, 0x65,
	0x6d, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02,
	0x52, 0x05, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x22, 0x49, 0x0a, 0x0c, 0x57, 0x61, 0x74, 0x63, 0x68,
	0x65, 0x64, 0x41, 0x6e, 0x69, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x6d, 0x61, 0x6b, 0x69, 0x2e, 0x49, 0x74,
	0x65, 0x6d, 0x52, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x12, 0x11, 0x0a, 0x01, 0x6b, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x05, 0x48, 0x00, 0x52, 0x01, 0x6b, 0x88, 0x01, 0x01, 0x42, 0x04, 0x0a, 0x02,
	0x5f, 0x6b, 0x22, 0x3f, 0x0a, 0x10, 0x52, 0x65, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x64, 0x65,
	0x64, 0x41, 0x6e, 0x69, 0x6d, 0x65, 0x12, 0x2b, 0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x6d, 0x61, 0x6b, 0x69, 0x2e, 0x52, 0x65, 0x63,
	0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x64, 0x65, 0x64, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x05, 0x69, 0x74,
	0x65, 0x6d, 0x73, 0x32, 0x5e, 0x0a, 0x15, 0x52, 0x65, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x64,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x45, 0x0a, 0x17,
	0x47, 0x65, 0x74, 0x41, 0x6e, 0x69, 0x6d, 0x65, 0x52, 0x65, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e,
	0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x12, 0x2e, 0x6d, 0x61, 0x6b, 0x69, 0x2e, 0x57,
	0x61, 0x74, 0x63, 0x68, 0x65, 0x64, 0x41, 0x6e, 0x69, 0x6d, 0x65, 0x1a, 0x16, 0x2e, 0x6d, 0x61,
	0x6b, 0x69, 0x2e, 0x52, 0x65, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x64, 0x65, 0x64, 0x41, 0x6e,
	0x69, 0x6d, 0x65, 0x42, 0x2f, 0x5a, 0x2d, 0x2e, 0x2f, 0x72, 0x69, 0x63, 0x6b, 0x79, 0x63, 0x6f,
	0x72, 0x74, 0x65, 0x2f, 0x6d, 0x61, 0x6b, 0x69, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x52,
	0x65, 0x63, 0x6f, 0x6d, 0x6d, 0x65, 0x6e, 0x64, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protos_recommend_service_proto_rawDescOnce sync.Once
	file_protos_recommend_service_proto_rawDescData = file_protos_recommend_service_proto_rawDesc
)

func file_protos_recommend_service_proto_rawDescGZIP() []byte {
	file_protos_recommend_service_proto_rawDescOnce.Do(func() {
		file_protos_recommend_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_protos_recommend_service_proto_rawDescData)
	})
	return file_protos_recommend_service_proto_rawDescData
}

var file_protos_recommend_service_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_protos_recommend_service_proto_goTypes = []interface{}{
	(*Item)(nil),             // 0: maki.Item
	(*RecommendedItem)(nil),  // 1: maki.RecommendedItem
	(*WatchedAnime)(nil),     // 2: maki.WatchedAnime
	(*RecommendedAnime)(nil), // 3: maki.RecommendedAnime
}
var file_protos_recommend_service_proto_depIdxs = []int32{
	0, // 0: maki.WatchedAnime.items:type_name -> maki.Item
	1, // 1: maki.RecommendedAnime.items:type_name -> maki.RecommendedItem
	2, // 2: maki.RecommendationService.GetAnimeRecommendations:input_type -> maki.WatchedAnime
	3, // 3: maki.RecommendationService.GetAnimeRecommendations:output_type -> maki.RecommendedAnime
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_protos_recommend_service_proto_init() }
func file_protos_recommend_service_proto_init() {
	if File_protos_recommend_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protos_recommend_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Item); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_recommend_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RecommendedItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_recommend_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WatchedAnime); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protos_recommend_service_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RecommendedAnime); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_protos_recommend_service_proto_msgTypes[2].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protos_recommend_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protos_recommend_service_proto_goTypes,
		DependencyIndexes: file_protos_recommend_service_proto_depIdxs,
		MessageInfos:      file_protos_recommend_service_proto_msgTypes,
	}.Build()
	File_protos_recommend_service_proto = out.File
	file_protos_recommend_service_proto_rawDesc = nil
	file_protos_recommend_service_proto_goTypes = nil
	file_protos_recommend_service_proto_depIdxs = nil
}
